# Generated by Django 3.2.5 on 2021-07-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_menuitems_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Main meal', 'Main meal'), ('Drinks', 'Drinks'), ('Dessert', 'Dessert')], max_length=200, null=True),
        ),
    ]
