# Generated by Django 3.2.5 on 2021-07-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210712_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
