# Generated by Django 3.2.5 on 2021-07-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
